module.exports.client = require('./tuneuptechnology/client')
module.exports.customers = require('./tuneuptechnology/customers')
module.exports.inventory = require('./tuneuptechnology/inventory')
module.exports.locations = require('./tuneuptechnology/locations')
module.exports.tickets = require('./tuneuptechnology/tickets')
