module.exports.Client = require('./tuneuptechnology/client')
module.exports.Customers = require('./tuneuptechnology/customers')
module.exports.Inventory = require('./tuneuptechnology/inventory')
module.exports.Locations = require('./tuneuptechnology/locations')
module.exports.Tickets = require('./tuneuptechnology/tickets')
